### ISSUE TITLE
Recommend to use branches instead of RC-1, Release folder

### ISSUE THREAD

**Issue by fu7mu4** [OpenChain-Project/Specification-Translation-JP#9]
This repository has RC-1 and Release folder in one branch.
I think that it is not usefull for everyone.
Please use branches instad of such folders

RC-1や Releaseフォルダがひとつのブランチの中にあります。
これは皆様にとって不便だと思いますので、
そのようなフォルダの代わりにブランチを切ることは可能でしょうかご検討ください。

**Comment by maabou512** [comment]
ご提案ありがとうございます。一度チームメンバに相談してみたいと思います。もしよろしければ、

> これは皆様にとって不便だと思いますので、

の部分について、RCやReleaseフォルダをブランチにすることでどういったメリットがあるか知りたいです。（こういった翻訳を想定した場合）どういったプロセスを想定されていているのか情報をいただければ大変助かります。（実は翻訳プロセスはチーム内で課題として認識されているのですが、どうすれば効率的・効果的に回るのかがなかなか結論が出ません）

Thanks for your proposal!
We would be happy if  you  can share  more information about why you think RC or Release documents should be maintained separetedly in branches , because  It has been an important issue  how translation process  should be in this team. Anyway, I will share this first request  to the translation team members.

**Comment by maabou512** [comment]
確かに、実際にフォルダ構成をみると翻訳作業者中心になっていて、翻訳ツールである「OmegaT」関連のフォルダが「どこに何があるのか」分かりづらくしているのかもしれないな、と感じました。

ただ、今の時点ではREADMEで全体のフォルダ構成のポイントは説明しているということで（そうはいっても、直感的なわかりづらさが残っているというとだと思います）、現状維持とさせてください。
ご提案の背景などがうかがえた段階で、改めて検討に入らせていただければと思います。

また、「RC/Release用のブランチを切る」というアイデア以外に「RC版についてはタグ付け」してわかるようにしておくというアイデアももらいました。その辺も含めて今後のプロセスに反映していければと考えております。ありがとうございました。

Actually, I can imagine that  OmegaT related folders/files are very confusing for you, and  make it difficult to identify released versions and RC versions. but let us keep current operation for now. We believe readers understand where released/RC versions by README. 

However, of course, given more information or explaination about your proposal  we disucss again how to be. Another guy gave me an idea to use tags for RC versions. this is also a proposal to be taken in consideration. 

Thanks again,
